# Generated by Django 3.0.4 on 2020-06-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200609_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
