# Generated by Django 3.0.4 on 2020-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200609_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pic',
        ),
        migrations.AddField(
            model_name='movie',
            name='contenteng',
            field=models.TextField(default='pusty'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster'),
        ),
    ]
