# Generated by Django 3.0.4 on 2020-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200612_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='contenteng',
        ),
        migrations.AddField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(default='usun', max_length=100),
        ),
    ]
