# Generated by Django 3.0.4 on 2020-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200612_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
