# Generated by Django 3.0.4 on 2020-06-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (2, 'Dama'), (1, 'Horror')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.ExtraInfo'),
        ),
    ]
