# Generated by Django 3.0.4 on 2020-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200615_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dama'), (1, 'Horror'), (0, 'Other')], default=0),
        ),
    ]
