# Generated by Django 3.0.4 on 2020-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20200615_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Other'), (2, 'Dama')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('films', models.ManyToManyField(to='movie.Movie')),
            ],
        ),
    ]
